### ISSUE TITLE
Data is precious,help me please!Thx

### ISSUE THREAD

**Issue by jk2573963** [Nameless-AOSP/OTA#43]
Hi, bro.I am using 05-22version now. I noticed that the log in the system update indicates that it cannot be updated to the 06-11version via OTA. Can I update via adb?
Or should I downgrade to oos12?
Data is precious,help me please!Thx

**Comment by RisaShiramine** [comment]
Use PayloadDumper extract img files manually and flash them via fastbootD

**Comment by manikantaraavi** [comment]
Use Fastboot installer or sideload ROM using ADB
