### ISSUE TITLE
[kebab] USB OTG devices do not get recognised at all

### ISSUE THREAD

**Issue by alexis-belmonte** [Nameless-AOSP/OTA#63]
Hi everyone, and thank you for taking the time to read my issue description.

I've been trying out Nameless AOSP as it is basically the best ROM available for my OnePlus 8T (KB05AA, LPDDR5 variant, 8GB/128GB) out of everything I've been trying so far.

Unfortunately, it seems that my USB devices (an external hard disk drive, a standard USB key, and a gamepad) through OTG do not get recognised by Android at all. I know this is not a kernel issue as I've tried to replace `boot.img` with an alternative one and it didn't work. Others ROMs seem to work fine with USB OTG devices, so I'm pretty confident that this issue is observable only on this ROM. Maybe there's a permissions file missing in `/system/etc/permissions/`, but I'm not an Android expert so this is just guessing at this point.

I'm available if you need more information or details, as I will keep an eye on it daily. I really, REALLY am grateful for the work that you guys have made up until this point, and I sincerely wish that we can find a solution to this.

Thanks for reading, and I hope you have a great day :]

**Comment by alexis-belmonte** [comment]
Upgrading to the latest build fixed the issue. Closing my ticket now.

**Comment by chandu078** [comment]
> 

Thank you for reporting. Hope you enjoying new build :)

**Comment by alexis-belmonte** [comment]
I do haha, you guys did a great job! :]
