### ISSUE TITLE
是否对加入第三方输入法震动的支持？

### ISSUE THREAD

**Issue by a757814283** [Nameless-AOSP/OTA#9]
昨天体验了下系统，非常惊艳，但是遇到了一个小问题，好像所有第三方输入法的震动都有问题，设置里面拉满了之后还是感觉很微妙，不知道这个问题有望修复吗？
一加8p，已更新到最新系统版本

**Comment by cjh1249131356** [comment]
第三方输入法比较难修复，没有一加底层的振动代码，振动很难调教成和官方一样。

**Comment by a757814283** [comment]
哦哦是这样，那好吧我去找找别的方案，但是有没有一种可能就是可以类似应用设置里面的伪装Pixel，伪装的方式让输入法识别本机为魅族或者OPPO机型从而开启输入法的mBack功能。

**Comment by cjh1249131356** [comment]
我没记错的话mBack是需要压感支持的吧。一加硬件不支持，伪装了也没用

**Comment by a757814283** [comment]
好吧谢谢
